--liquibase formatted sql

--changeset tattoo_kot:1.0.1
CREATE TABLE IF NOT EXISTS users(
    id VARCHAR PRIMARY KEY,
    name VARCHAR(100)
);

--changeset tattoo_kot:1.0.2
INSERT INTO users (id, name) VALUES (1, 'John');

--changeset tattoo_kot:1.0.3
-- Create table: Member
CREATE TABLE IF NOT EXISTS Member (
  MEMBER_PID SERIAL PRIMARY KEY,
  MEMBER_ID VARCHAR(255),
  MEMBER_ID_UPPER VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  FIRST_NAME_UPPER VARCHAR(255),
  LAST_NAME_UPPER VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  SUFFIX VARCHAR(255),
  TIMEZONE_CODE VARCHAR(255),
  CARD_ID VARCHAR(255),
  GENDER_ID BIGINT,
  CLIENT_CODE BIGINT,
  PRIM_LANG_CODE BIGINT,
  BIRTH_DATE DATE
);

-- Create table: Enrollment
CREATE TABLE IF NOT EXISTS Enrollment (
  ID SERIAL PRIMARY KEY,
  MEMBER_PID BIGINT,
  FOREIGN KEY (MEMBER_PID) REFERENCES Member(MEMBER_PID)
);

-- Create table: Address
CREATE TABLE IF NOT EXISTS Address (
  ID SERIAL PRIMARY KEY,
  MEMBER_PID BIGINT,
  FOREIGN KEY (MEMBER_PID) REFERENCES Member(MEMBER_PID)
);

-- Create table: MemberAlert
CREATE TABLE IF NOT EXISTS MemberAlert (
  ID SERIAL PRIMARY KEY,
  MEMBER_PID BIGINT,
  FOREIGN KEY (MEMBER_PID) REFERENCES Member(MEMBER_PID)
);

-- Create table: Email
CREATE TABLE IF NOT EXISTS Email (
  ID SERIAL PRIMARY KEY,
  MEMBER_PID BIGINT,
  FOREIGN KEY (MEMBER_PID) REFERENCES Member(MEMBER_PID)
);

-- Create table: MemberAlternateId
CREATE TABLE IF NOT EXISTS MemberAlternateId (
  ID SERIAL PRIMARY KEY,
  MEMBER_PID BIGINT,
  FOREIGN KEY (MEMBER_PID) REFERENCES Member(MEMBER_PID)
);

-- Create table: Phone
CREATE TABLE IF NOT EXISTS Phone (
  ID SERIAL PRIMARY KEY,
  MEMBER_PID BIGINT,
  FOREIGN KEY (MEMBER_PID) REFERENCES Member(MEMBER_PID)
);

-- Create table: Gender
CREATE TABLE IF NOT EXISTS Gender (
  GENDER_ID SERIAL PRIMARY KEY
);

-- Create table: Client
CREATE TABLE IF NOT EXISTS Client (
  CLIENT_CODE SERIAL PRIMARY KEY
);

-- Create table: Language
CREATE TABLE IF NOT EXISTS Language (
  LANG_ID SERIAL PRIMARY KEY
);

-- Add foreign key constraints
ALTER TABLE Member ADD CONSTRAINT FK_Gender FOREIGN KEY (GENDER_ID) REFERENCES Gender(GENDER_ID);
ALTER TABLE Member ADD CONSTRAINT FK_Client FOREIGN KEY (CLIENT_CODE) REFERENCES Client(CLIENT_CODE);
ALTER TABLE Member ADD CONSTRAINT FK_Language FOREIGN KEY (PRIM_LANG_CODE) REFERENCES Language(LANG_ID);
